### ISSUE TITLE
Day 284 Divide and Conquer Algorithm to Find Longest Substring with Character Count of at Least K

### ISSUE THREAD

**Issue by akhilub** [DoctorLai/Teaching-Kids-Programming#5]
Thank you for the beautiful explanation. I am learning so much along with Eric & Ryan.
In the blog for DIVIDE AND CONQUER ALGORITHM I believe you wanted to write on line 5

```
return max(self.longestSubstringAtLeastK(x, k) for x in s.split(c))
```
instead of 
```
return max(self.solve(x, k) for x in s.split(c))
```

Additionally for refering the problem in your collections this the problem on Leetcode.

https://leetcode.com/problems/longest-substring-with-at-least-k-repeating-characters/

**Comment by DoctorLai** [comment]
Thanks!
